export enum Routes {
  home = '/',
  About = '/about',
  Main = '/main',
  Showman = '/showman',
  Services = '/services',
  Show = '/show',
  Photographer = '/photographer',
  Dj = '/dj',
  Musicians = '/musicians',
  EquipmentRental = '/equipment-rental',
  CarsRental = '/cars-rental',
  CostumeRental = '/costume-rental',
  Signin = '/signin',
  Register = '/register',
  Setting = '/setting',
  ProfileSetting = '/profile-setting',
  Profile = '/profile',
  CreateEvent = '/event/create',
  Event = '/event',
  RequestList = '/request-list',
  ForgotPassword = '/forgot-password',
  Favorites = '/favorites',
  FloristsDecorators = '/florist-decorators',
  DancersEntertainers = '/dance-entertainers',
  Restaurants = '/restaurants',
  Cakes = '/cakes',
  Messages = '/messages',
  Categories = '/categories',
}

export enum ProfileRoutes {
  Profile = '/profile',
  Messages = '/profile/messages',
  Notification = '/profile/notifications',
  Requests = '/profile/requests',
  Events = '/profile/events',
  Favorites = '/profile/favorites',
  Payments = '/profile/payments',
  Professions = '/profile/professions',
}
